sinclude scripts/env.mk
ARCH := arch/x86

X_INCDIRS := include/ $(ARCH)/include/
CC := echo gcc
AS := echo as
LD := echo ld
export AS LD
export ARCH

SRC := $(ARCH)/ ipc/ task/ drivers/
NAME := kernel.elf
MODULE += $(ARCH)/

define CUSTOM_TARGET_CMD
$(CC) $(X_CCFLAGS) $(XOBJS); \
$(LD) $(X_LDFLAGS) -n -T $(ARCH)/kernel.ld -o $@ $(XOBJS)
endef